In [ ]:
# ctrl v to paste
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500_02_Fall2025/LC/L18"

/content/drive/MyDrive/Colab Notebooks/ANLY2500_02_Fall2025/LC/L18

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%ls

L18_LCP.ipynb  us-cities-top-1k.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500_02_Fall2025/LC/L18'

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv("us-cities-top-1k.csv") # ctrl c to copy
print(df)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
l=[2]*1000
print(l)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [ ]:
df["NC1"]=l

In [ ]:
print(df)

              City           State  Population        lat         lon  NC1
0       Marysville      Washington       63269  48.051764 -122.177082    2
1           Perris      California       72326  33.782519 -117.228648    2
2        Cleveland            Ohio      390113  41.499320  -81.694361    2
3        Worcester   Massachusetts      182544  42.262593  -71.802293    2
4         Columbia  South Carolina      133358  34.000710  -81.034814    2
..             ...             ...         ...        ...         ...  ...
995  West New York      New Jersey       52122  40.787879  -74.014306    2
996        Everett   Massachusetts       42935  42.408430  -71.053663    2
997         Linden      New Jersey       41301  40.622048  -74.244590    2
998      Asheville  North Carolina       87236  35.595058  -82.551487    2
999        Compton      California       97877  33.895849 -118.220071    2

[1000 rows x 6 columns]

In [ ]:
df["NC2"]=df["Population"]*1.03

In [ ]:
print(df)

              City           State  Population        lat         lon  NC1  \
0       Marysville      Washington       63269  48.051764 -122.177082    2
1           Perris      California       72326  33.782519 -117.228648    2
2        Cleveland            Ohio      390113  41.499320  -81.694361    2
3        Worcester   Massachusetts      182544  42.262593  -71.802293    2
4         Columbia  South Carolina      133358  34.000710  -81.034814    2
..             ...             ...         ...        ...         ...  ...
995  West New York      New Jersey       52122  40.787879  -74.014306    2
996        Everett   Massachusetts       42935  42.408430  -71.053663    2
997         Linden      New Jersey       41301  40.622048  -74.244590    2
998      Asheville  North Carolina       87236  35.595058  -82.551487    2
999        Compton      California       97877  33.895849 -118.220071    2

           NC2
0     65167.07
1     74495.78
2    401816.39
3    188020.32
4    137358.74
..         ...
995   53685.66
996   44223.05
997   42540.03
998   89853.08
999  100813.31

[1000 rows x 7 columns]

In [ ]:
df.to_csv("D1.csv",index=False)

In [ ]:
%ls

D1.csv  L18_LCP.ipynb  us-cities-top-1k.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500_02_Fall2025/LC/L18'

In [ ]:
%ls

D1.csv  L18_02.ipynb  us-cities-top-1k.csv

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv('us-cities-top-1k.csv')# RAM

In [ ]:
print(df1)
print(2+3)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]
5

In [ ]:
#
print(df1.columns)

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
# []
# tail head
df2=df1.tail(3) # RAM

In [ ]:
df2

          City           State  Population        lat         lon
997     Linden      New Jersey       41301  40.622048  -74.244590
998  Asheville  North Carolina       87236  35.595058  -82.551487
999    Compton      California       97877  33.895849 -118.220071

In [ ]:
df2.to_csv('last3.csv',index=True)

In [ ]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df1.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
df3=df1[['State','State','City']] # [] . result in a table RAM

In [ ]:
print(df3)

              State           State           City
0        Washington      Washington     Marysville
1        California      California         Perris
2              Ohio            Ohio      Cleveland
3     Massachusetts   Massachusetts      Worcester
4    South Carolina  South Carolina       Columbia
..              ...             ...            ...
995      New Jersey      New Jersey  West New York
996   Massachusetts   Massachusetts        Everett
997      New Jersey      New Jersey         Linden
998  North Carolina  North Carolina      Asheville
999      California      California        Compton

[1000 rows x 3 columns]

In [ ]:
df3.to_csv("c3.csv",index=True)

In [ ]:
df1['City'] # series single column

0         Marysville
1             Perris
2          Cleveland
3          Worcester
4           Columbia
           ...
995    West New York
996          Everett
997           Linden
998        Asheville
999          Compton
Name: City, Length: 1000, dtype: object

In [ ]:
#
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
[1,2]*3

[1, 2, 1, 2, 1, 2]

In [ ]:
[2.3]*10

[2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3]

In [ ]:
df1["NC1"]=["Tom"]*1000

In [ ]:
df1

              City           State  Population        lat         lon  NC1
0       Marysville      Washington       63269  48.051764 -122.177082  Tom
1           Perris      California       72326  33.782519 -117.228648  Tom
2        Cleveland            Ohio      390113  41.499320  -81.694361  Tom
3        Worcester   Massachusetts      182544  42.262593  -71.802293  Tom
4         Columbia  South Carolina      133358  34.000710  -81.034814  Tom
..             ...             ...         ...        ...         ...  ...
995  West New York      New Jersey       52122  40.787879  -74.014306  Tom
996        Everett   Massachusetts       42935  42.408430  -71.053663  Tom
997         Linden      New Jersey       41301  40.622048  -74.244590  Tom
998      Asheville  North Carolina       87236  35.595058  -82.551487  Tom
999        Compton      California       97877  33.895849 -118.220071  Tom

[1000 rows x 6 columns]

In [ ]:
df1['Population']+100# series

0       63369
1       72426
2      390213
3      182644
4      133458
        ...
995     52222
996     43035
997     41401
998     87336
999     97977
Name: Population, Length: 1000, dtype: int64

In [ ]:
df1["NC2"]=df1['Population']*1.03

In [ ]:
df1

,City,State,Population,lat,lon,NC1,NC2
0,Marysville,Washington,63269,48.051764,-122.177082,Tom,65167.07
1,Perris,California,72326,33.782519,-117.228648,Tom,74495.78
2,Cleveland,Ohio,390113,41.499320,-81.694361,Tom,401816.39
3,Worcester,Massachusetts,182544,42.262593,-71.802293,Tom,188020.32
4,Columbia,South Carolina,133358,34.000710,-81.034814,Tom,137358.74
...,...,...,...,...,...,...,...
995,West New York,New Jersey,52122,40.787879,-74.014306,Tom,53685.66
996,Everett,Massachusetts,42935,42.408430,-71.053663,Tom,44223.05
997,Linden,New Jersey,41301,40.622048,-74.244590,Tom,42540.03
998,Asheville,North Carolina,87236,35.595058,-82.551487,Tom,89853.08
999,Compton,California,97877,33.895849,-118.220071,Tom,100813.31

In [ ]:
# sort_values()
df1.sort_values(by=["Population"],ascending=[False])

,City,State,Population,lat,lon,NC1,NC2
890,New York,New York,8405837,40.712784,-74.005941,Tom,8658012.11
953,Los Angeles,California,3884307,34.052234,-118.243685,Tom,4000836.21
594,Chicago,Illinois,2718782,41.878114,-87.629798,Tom,2800345.46
646,Houston,Texas,2195914,29.760427,-95.369803,Tom,2261791.42
53,Philadelphia,Pennsylvania,1553165,39.952584,-75.165222,Tom,1599759.95
...,...,...,...,...,...,...,...
346,Weslaco,Texas,37093,26.159519,-97.990837,Tom,38205.79
722,Keizer,Oregon,37064,44.990119,-123.026208,Tom,38175.92
434,Spanish Fork,Utah,36956,40.114955,-111.654923,Tom,38064.68
552,Beloit,Wisconsin,36888,42.508348,-89.031777,Tom,37994.64
961,Panama City,Florida,36877,30.158813,-85.660206,Tom,37983.31