In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500_01_Fall2025/LC/L19"

/content/drive/MyDrive/Colab Notebooks/ANLY2500_01_Fall2025/LC/L19

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%ls

L19_LCP.ipynb  us-cities-top-1k.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500_01_Fall2025/LC/L19'

In [ ]:
import pandas as pd

In [ ]:
#
df1=pd.read_csv("us-cities-top-1k.csv")

In [ ]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
# filtering
# get one single column
c1=df1["State"]=="Utah"
print(c1)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: State, Length: 1000, dtype: bool

In [ ]:
df2=df1[c1]
print(df2)

                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047

In [ ]:
df2.to_csv("utah.csv",index=False)

In [ ]:
%ls

L19_LCP.ipynb  us-cities-top-1k.csv  utah.csv

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500_01_Fall2025/LC/L19"

/content/drive/MyDrive/Colab Notebooks/ANLY2500_01_Fall2025/LC/L19

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/ANLY2500_01_Fall2025/LC/L19'

In [ ]:
%ls

L19_01.ipynb  us-cities-top-1k.csv  utah.csv

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv("us-cities-top-1k.csv")

In [ ]:
print(df1)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df1.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
# sort_values()
# series: min() max() mean()
# filtering
df2=df1.sort_values(by=['Population'],ascending=[False])# create a new df in RAM

In [ ]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
df3=df2.head(10) # RAM

In [ ]:
df3

             City         State  Population        lat         lon
890      New York      New York     8405837  40.712784  -74.005941
953   Los Angeles    California     3884307  34.052234 -118.243685
594       Chicago      Illinois     2718782  41.878114  -87.629798
646       Houston         Texas     2195914  29.760427  -95.369803
53   Philadelphia  Pennsylvania     1553165  39.952584  -75.165222
966       Phoenix       Arizona     1513367  33.448377 -112.074037
153   San Antonio         Texas     1409019  29.424122  -98.493628
333     San Diego    California     1355896  32.715738 -117.161084
59         Dallas         Texas     1257676  32.776664  -96.796988
805      San Jose    California      998537  37.338208 -121.886329

In [ ]:
df3.to_csv("top10.csv",index=True)

In [ ]:
%ls

L19_01.ipynb  top10.csv  us-cities-top-1k.csv  utah.csv

In [ ]:
#
df1.columns

Index(['City', 'State', 'Population', 'lat', 'lon'], dtype='object')

In [ ]:
df1[['City', 'Population']] # creates a table

              City  Population
0       Marysville       63269
1           Perris       72326
2        Cleveland      390113
3        Worcester      182544
4         Columbia      133358
..             ...         ...
995  West New York       52122
996        Everett       42935
997         Linden       41301
998      Asheville       87236
999        Compton       97877

[1000 rows x 2 columns]

In [ ]:
s1=df1['Population'] # series, single column

In [ ]:
s1

0       63269
1       72326
2      390113
3      182544
4      133358
        ...
995     52122
996     42935
997     41301
998     87236
999     97877
Name: Population, Length: 1000, dtype: int64

In [ ]:
m1=s1.max()
m1 # print(m1)

8405837

In [ ]:
s1.min()

36877

In [ ]:
s1.mean()

np.float64(131132.443)

In [ ]:
s1.count()

np.int64(1000)

In [ ]:
s2=df1["State"]# series
s2

0          Washington
1          California
2                Ohio
3       Massachusetts
4      South Carolina
            ...
995        New Jersey
996     Massachusetts
997        New Jersey
998    North Carolina
999        California
Name: State, Length: 1000, dtype: object

In [ ]:
# unique()
states=s2.unique()

In [ ]:
states

array(['Washington', 'California', 'Ohio', 'Massachusetts',
       'South Carolina', 'Connecticut', 'Minnesota', 'Michigan',
       'Louisiana', 'Idaho', 'Indiana', 'Georgia', 'Colorado', 'Florida',
       'Illinois', 'Virginia', 'Texas', 'Kansas', 'Mississippi',
       'North Carolina', 'Missouri', 'New Mexico', 'Alabama', 'Utah',
       'Pennsylvania', 'New York', 'Wisconsin', 'Arkansas',
       'Rhode Island', 'Iowa', 'Nevada', 'Tennessee', 'Wyoming',
       'Maryland', 'North Dakota', 'Oregon', 'Arizona', 'Maine',
       'Nebraska', 'New Jersey', 'Montana', 'Oklahoma', 'West Virginia',
       'South Dakota', 'District of Columbia', 'New Hampshire', 'Alaska',
       'Delaware', 'Kentucky', 'Hawaii', 'Vermont'], dtype=object)

In [ ]:
len(states)

51

In [ ]:
s2.value_counts()

State
California              212
Texas                    83
Florida                  73
Illinois                 52
Massachusetts            36
Ohio                     33
Michigan                 31
Washington               28
Arizona                  25
Minnesota                24
North Carolina           22
New Jersey               22
Colorado                 21
Indiana                  21
Wisconsin                20
Utah                     19
Georgia                  18
New York                 17
Virginia                 17
Tennessee                17
Missouri                 16
Connecticut              15
Oregon                   14
Pennsylvania             13
Iowa                     13
South Carolina           12
Alabama                  12
Oklahoma                 11
Kansas                   11
Arkansas                 10
Louisiana                 9
Idaho                     8
New Mexico                7
Maryland                  7
Mississippi               6
Rhode Island              6
Nevada                    6
Kentucky                  5
North Dakota              4
Nebraska                  4
Montana                   4
New Hampshire             3
Wyoming                   2
Delaware                  2
West Virginia             2
South Dakota              2
Maine                     1
Alaska                    1
District of Columbia      1
Hawaii                    1
Vermont                   1
Name: count, dtype: int64

In [ ]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
# filtering
# all cities in utah
c1 = df1['State']=="Utah" #
#print(c1)

df2 = df1[c1] # table
df2.sort_values(by=["Population"],ascending=[False])

                 City State  Population        lat         lon
964    Salt Lake City  Utah      191180  40.760779 -111.891047
673  West Valley City  Utah      133579  40.691613 -112.001050
381             Provo  Utah      116288  40.233844 -111.658534
955       West Jordan  Utah      110077  40.609670 -111.939103
676              Orem  Utah       91648  40.296898 -111.694648
630             Sandy  Utah       90231  40.564978 -111.838973
533             Ogden  Utah       84249  41.223000 -111.973830
856        St. George  Utah       76817  37.096528 -113.568416
568            Layton  Utah       70790  41.060222 -111.971053
440      Taylorsville  Utah       60519  40.667725 -111.938826
193      South Jordan  Utah       59366  40.562170 -111.929658
500              Lehi  Utah       54382  40.391617 -111.850766
31              Logan  Utah       48913  41.736980 -111.833836
603            Murray  Utah       48612  40.666892 -111.887991
762            Draper  Utah       45285  40.524671 -111.863823
285         Bountiful  Utah       43023  40.889390 -111.880771
466          Riverton  Utah       40921  40.521893 -111.939102
737               Roy  Utah       37733  41.161611 -112.026331
434      Spanish Fork  Utah       36956  40.114955 -111.654923

In [ ]:
# and &
# or |
# not ~
c1 = df1['State']=="Nevada" #
c2 = df1['State']=="Utah" #
c3 = c1|c2
df1[c3]

                 City   State  Population        lat         lon
31              Logan    Utah       48913  41.736980 -111.833836
46          Henderson  Nevada      270811  36.039525 -114.981721
110              Reno  Nevada      233294  39.529633 -119.813803
193      South Jordan    Utah       59366  40.562170 -111.929658
194   North Las Vegas  Nevada      226877  36.198859 -115.117501
285         Bountiful    Utah       43023  40.889390 -111.880771
315            Sparks  Nevada       93282  39.534911 -119.752689
381             Provo    Utah      116288  40.233844 -111.658534
434      Spanish Fork    Utah       36956  40.114955 -111.654923
440      Taylorsville    Utah       60519  40.667725 -111.938826
447       Carson City  Nevada       54080  39.163798 -119.767403
466          Riverton    Utah       40921  40.521893 -111.939102
500              Lehi    Utah       54382  40.391617 -111.850766
533             Ogden    Utah       84249  41.223000 -111.973830
568            Layton    Utah       70790  41.060222 -111.971053
603            Murray    Utah       48612  40.666892 -111.887991
630             Sandy    Utah       90231  40.564978 -111.838973
673  West Valley City    Utah      133579  40.691613 -112.001050
676              Orem    Utah       91648  40.296898 -111.694648
712         Las Vegas  Nevada      603488  36.169941 -115.139830
737               Roy    Utah       37733  41.161611 -112.026331
762            Draper    Utah       45285  40.524671 -111.863823
856        St. George    Utah       76817  37.096528 -113.568416
955       West Jordan    Utah      110077  40.609670 -111.939103
964    Salt Lake City    Utah      191180  40.760779 -111.891047

In [ ]:
# Pop > 1 million
c1=df1['Population']>1000000
c2 = df1['State']=="Texas" #
c3= c1 & c2
df1[c3]

            City  State  Population        lat        lon
59        Dallas  Texas     1257676  32.776664 -96.796988
153  San Antonio  Texas     1409019  29.424122 -98.493628
646      Houston  Texas     2195914  29.760427 -95.369803

In [ ]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]